version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: cobble-tv-db
    volumes:
      - ./containers/database/postgres/volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - cobble-tv-backend

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./containers/bucket/minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - cobble-tv-backend

  minio-console:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin123); do
        sleep 2;
      done;
      exec /usr/bin/mc mb local/development-bucket;
      "
    networks:
      - cobble-tv-backend

volumes:
  minio_data:


networks:
  cobble-tv-backend:
    driver: bridge
